### ISSUE TITLE
Migrate App away from flat file data hydration

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/find-benefits-and-services#22]

**Comment by smcmurtry** [comment]
Do we need to make any code changes for this? I already set the environment variable `STAGING = "true"` for our heroku review apps and https://find-benefits-and-services.herokuapp.com.

If we leave the data.json file and associated features in, it might be a useful for another department, and would be less work for us.

**Comment by brdunfield** [comment]
I think as long as we document it, it should be fine to leave it as a feature flag with the STAGING var. We may want to consider renaming STAGING though? Otherwise I agree, probably no code changes needed.

**Comment by brdunfield** [comment]
Rename to: USEAIRTABLE

**Comment by brdunfield** [comment]
Doc changes have been made.
